// Generated by CoffeeScript 1.9.3
(function() {
  var db;

  db = require('./db');

  db.albums.find({}, {}, function(err, data) {
    if (err != null) {
      console.log("Error: failure to retrieve albums.");
    } else {
      console.log(data);
      return data;
    }
  }).sort({
    'play_counts': -1
  }).limit(20);

}).call(this);
