// Generated by CoffeeScript 1.9.3
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(req, res) {
    res.writeHead(200);
    res.end('Hello Http');
  });

  server.listen(8080);

}).call(this);
