// Generated by CoffeeScript 1.9.3
(function() {
  var MongoClient, mongodb, url;

  mongodb = require('mongodb');

  MongoClient = mongodb.MongoClient;

  url = 'mongodb://localhost:27017/my_database_name';

  MongoClient.connect(url, function(err, db) {
    if (err) {
      console.log('Unable to connect to the mongoDB server. Error:', err);
    } else {
      console.log('Connection established to', url);
    }
    db.close();
  });

}).call(this);
